### ISSUE TITLE
Workshop vs. Presentation directories

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/tomesh.101#13]
@dcwalk Should this be in `workshops` or `presentations`?
https://github.com/tomeshnet/tomesh.101/tree/master/presentations/20160821_build-a-mesh-node

**Comment by dcwalk** [comment]
Oh, haha.
I think if there are facilitation/additional materials it should be in workshop...? 
But if you just have slides, as this one, then presentations?

**Comment by benhylau** [comment]
Okay!
