### ISSUE TITLE
Record our terminology and develop glossary

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/tomesh.101#4]
Okay, here were the terms I highlighted form the presentation that would likely be new to beginners:
- topology
- node, edge, link, route, hop
- networking terms: routing, protocol, propagate, multiplexing, ethernet frames... 
- radio terminology: point to point, dBm, gain, radio, EIRP, frequency, band (spectrum)...
- types of antennas: omnidirectional, isotropic...
- mesh terms: cdjns, routing table, mesh point, 802.11s, peers, auto-peering, tunneling

Perhaps for strategies to approach, we could consider:
- not using domain-specific terms to introduce concepts
- having a supplemental glossary
- choosing a few key terms (and limiting ourselves that) per 'module'
- having a technique to allow people to let us know in a non-intimidating way that we are using jargon

**Comment by dcwalk** [comment]
From our intro to networks workshop...

Parts of a network
- Link
- Node

Moving around a network  
- Hop
- Route/Path
- Data/Packet

Common topologies (physical vs. conceptual), for conceptual bucketed as:
- centralized;
- decentralized;
- distributed

**Comment by Famicoman** [comment]
@dcwalk Do you think this can be closed by #18?

**Comment by dcwalk** [comment]
Totally @Famicoman! 🎉
